### PR TITLE
added games model

### PR DESCRIPTION
**Pull request by punkleia**
Work in progress!

### CODE REVIEW

**Comment by jacobwgillespie** [comment]
For this kind of a merge conflict, rather than editing the `db/schema.rb` file by hand, simply merging in master and running migrations should resolve the issue:

```
$ git checkout create-models
$ git pull origin master
$ rails db:migrate
$ git add .
$ git commit
```

**Comment by punkleia** [comment]
I created database models for Games and Pieces.  Take a look and give me a thumbs up if you're okay with me merging it.
Thanks!

**Comment by jacobwgillespie** [comment]
Looks like there's a Rubocop error - you can fix it by removing the space at the end of the line, and for the future, you can make Sublime automatically remove those spaces on save with the settings described at https://github.com/team-LetTheWookieWin/chess-app/pull/12#discussion_r116075504.

**Comment by punkleia** [comment]
@jacobwgillespie I added the code that you laid out in commit #12 to my preferences file, saved and updated everything, restarted the server, and it looks like I'm still failing on the same thing.  Do you have any suggestions?

Thanks!

**Comment by ihorie** [comment]
@punkleia The build fails because empty line is added to app/models/game.rb. Rubocop doesn't like that.
```rb
 class Game < ApplicationRecord
 
  end
```

Please see http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Style/EmptyLinesAroundBody for more detail.

**Comment by jacobwgillespie** [comment]
Running the following should automatically fix, or you can remove the blank line in the middle of the class.

```bash
$ bundle exec rubocop -a
```

**Comment by punkleia** [comment]
Thanks @ihorie and @jacobwgillespie!

**Comment by ihorie** [comment]
LGTM!

**Pull request merged**
