### PR TITLE
Rook move_valid?

### PR DESCRIPTION
**Pull request by jacobwgillespie**
This should implement `move_valid?` for the rook

### CODE REVIEW

**Comment by DrKalen** [comment]
Looks good to me. But does this mean we need to change the bishop etc. moves to allow moving on top of an opposing piece but not a friendly piece (instead of just avoiding moving where the path is obstructed)?

**Comment by tynahuynh** [comment]
LGTM

**Comment by punkleia** [comment]
@DrKalen Yes.  An opposing piece does not block your path (presumably because you can capture it?) But there's no legal way to pass through one of your own.

**Comment by jacobwgillespie** [comment]
> But does this mean we need to change the bishop etc. moves to allow moving on top of an opposing piece but not a friendly piece

Eventually yes, I think, depending on how capturing works.

> An opposing piece does not block your path (presumably because you can capture it?)

An opposing piece _does_ block your path - this only allows landing on one (to capture it).  But you can't move through any pieces, regardless of color.

**Pull request merged**
