### PR TITLE
Chessboard layout complete

### PR DESCRIPTION
**Pull request by Jorge-FHP**
Ok I think this is good 😄

### CODE REVIEW

**Comment by punkleia** [comment]
Sweet!  I have one more question.  Should one of these two be white?  

`+#chessboard tr:nth-child(2n) td:nth-child(2n+1) {
 +  background: black;
 +}
 +
 +#chessboard tr:nth-child(2n+1) td:nth-child(2n) {
 +  background: black;
 +}`

**Comment by Jorge-FHP** [comment]
No, let's say I want to change that second line of code `#chessboard tr:nth-child(2n+1) td:nth-child(2n) { background: black;}` to blue it would look like this:
screen shot 2017-05-19 at 10 59 48 am

**Comment by punkleia** [comment]
Woah! Cool. I think you're good to merge!

**Comment by Jorge-FHP** [comment]
I know it's not perfect but I had little time to work on it because of the issue I had with vagrant, but if anybody wants to do it a different way it's fine by me 😄

**Pull request merged**
